FROM redash/redash:10.1.0.b50633
COPY redash/query_runner/snowflake_keypair_env.py /app/redash/query_runner/
WORKDIR /app
CMD /usr/local/bin/gunicorn -b 0.0.0.0:$PORT --name redash -w${REDASH_WEB_WORKERS:-1} redash.wsgi:app
