FROM redash/redash:10.1.0.b50633
RUN pip install snowflake-connector-python cryptography
COPY redash/query_runner/snowflake_keypair_env.py /app/redash/query_runner/

WORKDIR /app

CMD ./manage.py rq scheduler
