FROM redash/redash:10.1.0.b50633
RUN pip install snowflake-connector-python cryptography
COPY redash/query_runner/snowflake_keypair_env.py /app/redash/query_runner/
COPY sitecustomize.py /app/sitecustomize.py
RUN python -c "import os, site, shutil; shutil.copy('/app/sitecustomize.py', os.path.join(site.getsitepackages()[0], 'sitecustomize.py'))"

ENV WORKERS_COUNT=${WORKERS_COUNT:-1}
ENV QUEUES="queries scheduled_queries schemas periodic emails default"

WORKDIR /app

CMD exec supervisord -c worker.conf
