FROM redash/redash:10.1.0.b50633
COPY redash/query_runner/snowflake_keypair_env.py /app/redash/query_runner/

ENV WORKERS_COUNT=${WORKERS_COUNT:-1}
ENV QUEUES="queries scheduled_queries schemas periodic emails default"

WORKDIR /app

CMD exec supervisord -c worker.conf
